---
title: "2 · Exercise 1a: Variables & variable types"
---

::: {.milestone}
**Block 1** · Learning goals: Understand what a variable is in Python & different types of variables.  
:::

::: {.callout-tip collapse="true" title="Make a new Python program & save the file"}

Create a new Python code file in the Coder on UCloud.

Save the file in /work/cogsci_methods01_e26 (or whatever you have named your methods cosgci folder).

:::

Now complete the following coding exercises in this file. 

::: {.callout-tip collapse="true" title="Make a variable and inspect its value in the console"}

Make any variable of any type.

Print the value of the variable to the console.

Add a comment above the variable to describe it.

Print the variable type to the console. 

:::

::: {.callout-tip collapse="true" title="Data Type 1: Regular string variables"}

Print the character string "Null hypothesis: Eating ice cream does not improve mood"

Store this expression in a variable called `null_hypothesis`

Print the first four characters of this string variable. 

Print the last four characters of this string variable. 

:::

::: {.callout-tip collapse="true" title="String methods"}

Split the variable `null_hypothesis` by spaces and store the output in a new variable called `split_var`. 

Print split_var[1]`  to the console. What is the output? 
Can you explain what function of the square brackets is? 
And the index inside of them? 

Can you index the second character in split_var[1]?

Split the string variable by the colon (:) character and store the output in a new variable.

Replace the lower case h in the `null_hypothesis` character string with an upper case H. 

Index the word 'hypothesis' in the `split_var` variable and store the output in a new variable called `hypothesis_word`

Convert `hypothesis_word` to all upper case characters and store in a new variabled called `hypothesis_word_upper`

Replace the word 'hypothesis' in the variable `null_hypothesis` with `hypothesis_word_upper`

Test whether `hypothesis_word_upper` starts with `H`

Get the length of `null_hypothesis`

There's lots more that you can do with strings, but these are the basics!

:::


::: {.callout-tip collapse="true" title="Data Type 2: Regular numeric variables"}

Okay, now let's turn to our other fundamental variable type: numeric. There are two basic types of numeric variables: 

1. Integers: Whole numbers (no decimal point)
2. Floating points: Numbers with a decimal point

```python

# this is an integer.
a = 1
type(a)

# this is a floating point.
b = 1.5 
type (b)

# this is also a floating point. Why?
c = 1.00
type(c) 

# what happens when you perform operations?
d = b + c
type(d)

# even when operations on two floats produce a whole number, the output will be represented as a floating point (i.e., with a decimal)
e = 1.5 + 1.5
type(e)

```

Standard numeric operations are addition (shown above), subtraction, multiplication and division. Below you can see the operators used for these.

```python
# for subtraction use '-'
print(a - b)

# for multiplication, use '*'
print(a * b)

# for division use '/'
print(a / b)


```

:::

::: {.callout-tip collapse="true" title="Printing variables"}

Imagine that you want to print reaction times for a given subject on an experiment screen.

The subject is different in each experiment, and so is their reaction time. 

You can create a special expression called an "f-string" where you embed the subject ID variable and the reaction time variable in a string. 

Start the string with `f`, then place the variable names inside curly brackets: `{}`.

```python
reaction_time = 0.45
message = f"Reaction time for {subject_id}: {reaction_time:.2f} seconds"
print(message)
```
In this example `{subject_id} inserts the value of the subject ID variable in the string and `{reaction_time:.2f}` inserts the value of `reaction_time`. The `.2f` formats the number with two digits after the decimal point.

This prints `Reaction time for S_10: 0.45 seconds`.

:::


